<a href="https://colab.research.google.com/github/sapan01/Machine-Learnings/blob/main/numpy_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
ar = np.array([[2,3,4],[5,6,7],[8,9,10],[11,12,13]])
print(ar)
print(ar.shape)
print(ar.size)
print(ar.ndim) 

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]
(4, 3)
12
2


In [ ]:
#3d matrix
import numpy as np
ar = np.array([[[2,3,4],[5,6,7],[8,9,10]],[[11,12,13],[14,15,16],[17,18,19]]])
print(ar)
print(ar.shape)
print(ar.size)
print(ar.ndim) #return dimension of array

[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]
(2, 3, 3)
18
3


In [ ]:
new_ar = np.arange(24).reshape(3,2,4)
print(ar)

[[[ 2  3  4]
  [ 5  6  7]
  [ 8  9 10]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]]


In [ ]:
#DTYPE
import numpy as np
a = np.array([[2,3,4],[4,5,6]])
print(a)
print(a.dtype)
b = np.array([1.2, 3.5, 5.1])
print(b)
print(b.dtype)

a = np.array([1,2,3,4])  # RIGHT
b = np.array([[1.5,2,3], [4,5,6]])
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print(b)
print(c)


[[2 3 4]
 [4 5 6]]
int64
[1.2 3.5 5.1]
float64
[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1.+0.j 2.+0.j]
 [3.+0.j 4.+0.j]]


In [ ]:
e =np.empty((2,3))
print(e)
e = np.ones((4,8))
print(e)
e = np.zeros((4,8),dtype=int)
print(e)

[[1.5 2.  3. ]
 [4.  5.  6. ]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [ ]:
af = ar.flatten()
print(af)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
a = np.arange(0,15,5) # 0to15 is range wirh differnce 5
print(a)
a = np.arange(0,50,5)
print(a)
a.resize(5,2)
print(a)
a= np.random.random((2,3))
print(a)

[ 0  5 10]
[ 0  5 10 15 20 25 30 35 40 45]
[[ 0  5]
 [10 15]
 [20 25]
 [30 35]
 [40 45]]
[[0.92679905 0.29544633 0.92115932]
 [0.68091933 0.38955886 0.42863436]]


In [ ]:
from numpy import *
arr =array([1,2,3,4])
arr = arr+5
print(arr)

[6 7 8 9]


In [ ]:
from numpy import *
arr1 =array([1,2,3,4])
arr2 = array([2,3,4,5])
arr = arr1+arr2
print(arr)

[3 5 7 9]


In [ ]:
from numpy import *
arr1 =array([1,2,3,4])
print(sin(arr))
print(cos(arr))
print(sqrt(arr))
print(min(arr))

[ 0.14112001 -0.95892427  0.6569866   0.41211849]
[-0.9899925   0.28366219  0.75390225 -0.91113026]
[1.73205081 2.23606798 2.64575131 3.        ]
3


In [ ]:
from numpy import *
arr1 = array([1,2,3])
arr2=arr1
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
arr2= arr1.view()#this is shallow copy #copying array in thhis way array will get different memory
arr1[2] = 5
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))
arr2 = arr1.copy() # deep copy (changes in one array will not change in another array)
arr1[2] = 23
print(arr1)
print(arr2)
print(id(arr1))
print(id(arr2))


[1 2 3]
[1 2 3]
139913582254480
139913582254480
[1 2 5]
[1 2 5]
139913582254480
139913582255200
[ 1  2 23]
[1 2 5]
139913582254480
139913582255040
